language: ruby
rvm:
  - 2.6
branches:
  only:
  - master
cache: bundler
sudo: false
addons:
  postgresql: "9.4"
env:
  - DATABASE_URL_TEST=postgresql://localhost/tove_test?user=postgres

before_script:
  - psql -c 'create database tove_test;' -U postgres
  - scripts/no_focus.sh

script: "bundle exec rspec"
